#!/usr/bin/env bash
# This Provides details about subdomains

retrieve_info() {
	local domain="$1"
	local subdomain="$2"

	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi

	for sub in "${subdomains[@]}"; do
        	string=$(dig +noall +answer "$sub.$domain")
        	record=$(echo "$string" | awk '{ print $4 }')
        	destination=$(echo "$string" | awk '{ print $5 }')
		echo "The subdomain $sub is a $record record and points to $destination"
    	done
}

main() {
    	if [ "$#" -lt 1 ]; then
        	echo "Usage: $0 <domain> [subdomain]"
        	exit 1
    	fi

    	local domain="$1"
    	local subdomain="$2"

    	retrieve_info "$domain" "$subdomain"
}

main "$@"

