#!/usr/bin/env bash

# A Bash script that configures a new Ubuntu machine and 
#	Install nginx on on server web-01


apt-get update
# Updated package list and install nginx
apt-get install -y nginx
ufw allow 'Nginx HTTP'
# Restart nginx (without using systemctl)
service nginx --full-restart
echo "Hello World!" > /var/www/html/index.html
