#!/usr/bin/env bash
#This is a a Bash script that displays Best School 10 times, but for
	the 9th iteration, displays Best School and Hi on a new line.

counter=0

while [ "$counter" -lt 10 ];
do
    if [ "$counter" -eq 8 ];
    then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi
    ((counter++))
done
